# Generated by Django 4.1.5 on 2023-01-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название объекта"),
                ),
                (
                    "adress",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Адрес объекта"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "electricity",
                    models.BooleanField(default=False, verbose_name="Электричество"),
                ),
                ("water", models.BooleanField(default=False, verbose_name="Вода")),
                ("gas", models.BooleanField(default=False, verbose_name="Газ")),
                ("kv", models.BooleanField(default=False, verbose_name="Квартплата")),
                ("tbo", models.BooleanField(default=False, verbose_name="ТБО")),
                ("domofon", models.BooleanField(default=False, verbose_name="Домофон")),
                ("inet", models.BooleanField(default=False, verbose_name="Интернет")),
                (
                    "other",
                    models.BooleanField(default=False, verbose_name="Другой платеж"),
                ),
            ],
            options={"verbose_name": "Объект", "verbose_name_plural": "Обьекты",},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=50, verbose_name="Предмет расчета"),
                ),
                (
                    "is_counter",
                    models.BooleanField(
                        default=False, verbose_name="Расчет по счетчику (Да/Нет)"
                    ),
                ),
                (
                    "day_night",
                    models.BooleanField(
                        default=False, verbose_name="Счетчик день-ночь (Да/Нет)"
                    ),
                ),
                (
                    "discrete_tarif",
                    models.BooleanField(
                        default=False,
                        verbose_name="Тариф зависит от потребления (Да/Нет)",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.appartment",
                        verbose_name="Объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет расчета",
                "verbose_name_plural": "Предметы расчета",
            },
        ),
        migrations.CreateModel(
            name="ToPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Расчет для оплаты")),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("1", "Январь"),
                            ("2", "Февраль"),
                            ("3", "Март"),
                            ("4", "Апрель"),
                            ("5", "Май"),
                            ("6", "Июнь"),
                            ("7", "Июль"),
                            ("8", "Август"),
                            ("9", "Сентябрь"),
                            ("10", "Октябрь"),
                            ("11", "Ноябрь"),
                            ("12", "Декабрь"),
                        ],
                        max_length=2,
                        verbose_name="Месяц расчета",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.item",
                        verbose_name="Предмет расчета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчетная сумма для оплаты",
                "verbose_name_plural": "Расчеты для оплаты",
            },
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Тариф")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Действующий тариф"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.item",
                        verbose_name="Предмет расчета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф для расчета",
                "verbose_name_plural": "Тарифы для расчета",
            },
        ),
        migrations.CreateModel(
            name="Payed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Оплачено")),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("1", "Январь"),
                            ("2", "Февраль"),
                            ("3", "Март"),
                            ("4", "Апрель"),
                            ("5", "Май"),
                            ("6", "Июнь"),
                            ("7", "Июль"),
                            ("8", "Август"),
                            ("9", "Сентябрь"),
                            ("10", "Октябрь"),
                            ("11", "Ноябрь"),
                            ("12", "Декабрь"),
                        ],
                        max_length=2,
                        verbose_name="Месяц расчета",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.item",
                        verbose_name="Предмет расчета",
                    ),
                ),
            ],
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты",},
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_provider",
                    models.CharField(
                        max_length=50, verbose_name="Название организации"
                    ),
                ),
                (
                    "item_user_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Лицевой счет"
                    ),
                ),
                (
                    "item_comment",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.appartment",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.item",
                        verbose_name="Предмет расчета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация для расчетов",
                "verbose_name_plural": "Информация для расчетов",
            },
        ),
        migrations.CreateModel(
            name="DiscreteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frm", models.PositiveSmallIntegerField(verbose_name="От")),
                ("to", models.PositiveSmallIntegerField(verbose_name="До")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.tarif",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дискретный тариф для расчета",
                "verbose_name_plural": "Дискретные тарифы для расчета",
            },
        ),
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Долг")),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("1", "Январь"),
                            ("2", "Февраль"),
                            ("3", "Март"),
                            ("4", "Апрель"),
                            ("5", "Май"),
                            ("6", "Июнь"),
                            ("7", "Июль"),
                            ("8", "Август"),
                            ("9", "Сентябрь"),
                            ("10", "Октябрь"),
                            ("11", "Ноябрь"),
                            ("12", "Декабрь"),
                        ],
                        max_length=2,
                        verbose_name="Месяц расчета",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.item",
                        verbose_name="Предмет расчета",
                    ),
                ),
            ],
            options={"verbose_name": "Долг", "verbose_name_plural": "Долги",},
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(verbose_name="Показания счетчика"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата ввода показаний"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compay.item",
                        verbose_name="Предмет расчета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показания счетчика",
                "verbose_name_plural": "Показания счетчиков",
            },
        ),
    ]
