# Generated by Django 4.1.5 on 2023-01-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appartment",
            options={
                "ordering": ["name"],
                "verbose_name": "Объект",
                "verbose_name_plural": "Обьекты",
            },
        ),
        migrations.AlterModelOptions(
            name="counter",
            options={
                "ordering": ["created"],
                "verbose_name": "Показания счетчика",
                "verbose_name_plural": "Показания счетчиков",
            },
        ),
        migrations.AlterModelOptions(
            name="debts",
            options={
                "ordering": ["created"],
                "verbose_name": "Долг",
                "verbose_name_plural": "Долги",
            },
        ),
        migrations.AlterModelOptions(
            name="discreteconfiguration",
            options={
                "ordering": ["created"],
                "verbose_name": "Дискретный тариф для расчета",
                "verbose_name_plural": "Дискретные тарифы для расчета",
            },
        ),
        migrations.AlterModelOptions(
            name="info",
            options={
                "ordering": ["created"],
                "verbose_name": "Информация для расчетов",
                "verbose_name_plural": "Информация для расчетов",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["item_name"],
                "verbose_name": "Предмет расчета",
                "verbose_name_plural": "Предметы расчета",
            },
        ),
        migrations.AlterModelOptions(
            name="payed",
            options={
                "ordering": ["created"],
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
            },
        ),
        migrations.AlterModelOptions(
            name="tarif",
            options={
                "ordering": ["active"],
                "verbose_name": "Тариф для расчета",
                "verbose_name_plural": "Тарифы для расчета",
            },
        ),
        migrations.AlterModelOptions(
            name="topay",
            options={
                "ordering": ["created"],
                "verbose_name": "Расчетная сумма для оплаты",
                "verbose_name_plural": "Расчеты для оплаты",
            },
        ),
    ]
