# Generated by Django 4.1.5 on 2023-02-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topay", models.FloatField(default=0, verbose_name="К оплате")),
                ("payed", models.FloatField(default=0, verbose_name="Оплачено")),
                ("debt", models.FloatField(default=0, verbose_name="Долг по месяцу")),
                (
                    "debt_summary",
                    models.FloatField(default=0, verbose_name="Долг итоговый"),
                ),
                (
                    "debt_sum_before",
                    models.FloatField(default=0, verbose_name="Долг предыдущий"),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("1", "Январь"),
                            ("2", "Февраль"),
                            ("3", "Март"),
                            ("4", "Апрель"),
                            ("5", "Май"),
                            ("6", "Июнь"),
                            ("7", "Июль"),
                            ("8", "Август"),
                            ("9", "Сентябрь"),
                            ("10", "Октябрь"),
                            ("11", "Ноябрь"),
                            ("12", "Декабрь"),
                        ],
                        max_length=2,
                        verbose_name="Месяц расчета",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compay.appartment",
                        verbose_name="Имя объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Суммарный расчет",
                "verbose_name_plural": "Суммарный расчет",
                "ordering": ["created"],
            },
        ),
    ]
