# Generated by Django 4.1.5 on 2023-02-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0002_alter_appartment_options_alter_counter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["item_name"],
                "verbose_name": "Конфигурация для расчета",
                "verbose_name_plural": "Конфигурации для расчета",
            },
        ),
        migrations.AddField(
            model_name="counter",
            name="type",
            field=models.CharField(
                choices=[("flat", "Однотарифный"), ("day", "День"), ("night", "Ночь")],
                default="flat",
                max_length=15,
                verbose_name="Название организации",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(
                choices=[
                    ("electricity", "Электричество"),
                    ("water", "Вода"),
                    ("gas", "Газ"),
                    ("kv", "Квартплата"),
                    ("tbo", "ТБО"),
                    ("domofon", "Домофон"),
                    ("inet", "Интернет"),
                    ("other", "Другой вид оплаты"),
                ],
                max_length=50,
                verbose_name="Предмет расчета",
            ),
        ),
    ]
