# Generated by Django 4.1.5 on 2023-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0002_paysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
    ]
