# Generated by Django 4.1.5 on 2023-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0003_alter_item_options_counter_type_alter_item_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarif",
            name="type",
            field=models.CharField(
                choices=[
                    ("flat", "Однотарифный"),
                    ("day", "День"),
                    ("night", "Ночь"),
                    ("discrete1", "Тариф1"),
                    ("discrete2", "Тариф2"),
                    ("discrete3", "Тариф3"),
                ],
                default="flat",
                max_length=15,
                verbose_name="Тип тарифа",
            ),
        ),
        migrations.AlterField(
            model_name="counter",
            name="type",
            field=models.CharField(
                choices=[("flat", "Однотарифный"), ("day", "День"), ("night", "Ночь")],
                default="flat",
                max_length=15,
                verbose_name="Тип счетчика",
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="value",
            field=models.FloatField(verbose_name="Значение"),
        ),
    ]
