# Generated by Django 4.1.5 on 2023-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0003_item_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="counter",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ед.", "ед."),
                    ("м3", "м3"),
                    ("тыс.м3", "тыс.м3"),
                    ("кВт", "кВт"),
                ],
                default="ед.",
                max_length=15,
                verbose_name="Ед.изм.",
            ),
        ),
        migrations.AddField(
            model_name="pay",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("руб", "руб")],
                default="руб",
                max_length=15,
                verbose_name="Ед.изм.",
            ),
        ),
        migrations.AddField(
            model_name="paysummary",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("руб", "руб")],
                default="руб",
                max_length=15,
                verbose_name="Ед.изм.",
            ),
        ),
        migrations.AddField(
            model_name="tarif",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("руб", "руб"),
                    ("руб/м3", "руб/м3"),
                    ("руб/кВт", "руб/кВт"),
                    ("руб/тыс.м3", "руб/тыс.м3"),
                ],
                default="руб",
                max_length=15,
                verbose_name="Ед.изм.",
            ),
        ),
    ]
