# Generated by Django 4.1.5 on 2023-02-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0004_tarif_type_alter_counter_type_alter_tarif_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appartment",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Название объекта"
            ),
        ),
        migrations.AlterField(
            model_name="counter",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.item",
                verbose_name="Предмет расчета",
            ),
        ),
        migrations.AlterField(
            model_name="debts",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.item",
                verbose_name="Предмет расчета",
            ),
        ),
        migrations.AlterField(
            model_name="discreteconfiguration",
            name="tarif",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.tarif",
                verbose_name="Тариф",
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.item",
                verbose_name="Предмет расчета",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.appartment",
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="payed",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.item",
                verbose_name="Предмет расчета",
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.item",
                verbose_name="Предмет расчета",
            ),
        ),
        migrations.AlterField(
            model_name="topay",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compay.item",
                verbose_name="Предмет расчета",
            ),
        ),
    ]
