# Generated by Django 4.1.5 on 2023-02-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0005_alter_appartment_name_alter_counter_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="is_counter",
            field=models.CharField(
                choices=[("counter", "Счетчик"), ("tarif", "Тариф")],
                default="tarif",
                max_length=50,
                verbose_name="Расчет",
            ),
        ),
    ]
