# Generated by Django 4.1.5 on 2023-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0006_alter_item_is_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="counter",
            name="previous",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Предыдущие показания"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_counter",
            field=models.CharField(
                choices=[("counter", "Счетчик"), ("tarif", "Тариф")],
                default="tarif",
                max_length=50,
                verbose_name="Расчет по",
            ),
        ),
    ]
