# Generated by Django 4.1.5 on 2023-02-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0007_counter_previous_alter_item_is_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarif",
            options={
                "ordering": ["-created"],
                "verbose_name": "Тариф для расчета",
                "verbose_name_plural": "Тарифы для расчета",
            },
        ),
        migrations.RemoveField(model_name="item", name="day_night",),
        migrations.RemoveField(model_name="item", name="discrete_tarif",),
        migrations.RemoveField(model_name="tarif", name="active",),
        migrations.AddField(
            model_name="appartment",
            name="el_counter_discrete",
            field=models.BooleanField(
                default=False, verbose_name="Тариф зависит от потребления (Да/Нет)"
            ),
        ),
        migrations.AddField(
            model_name="appartment",
            name="el_is_counter",
            field=models.CharField(
                choices=[("counter", "Счетчик"), ("tarif", "Тариф")],
                default="tarif",
                max_length=50,
                verbose_name="Расчет по",
            ),
        ),
        migrations.AddField(
            model_name="appartment",
            name="el_night",
            field=models.BooleanField(
                default=False, verbose_name="Счетчик день-ночь (Да/Нет)"
            ),
        ),
        migrations.AddField(
            model_name="appartment",
            name="gas_is_counter",
            field=models.CharField(
                choices=[("counter", "Счетчик"), ("tarif", "Тариф")],
                default="tarif",
                max_length=50,
                verbose_name="Расчет по",
            ),
        ),
        migrations.AddField(
            model_name="appartment",
            name="wat_is_counter",
            field=models.CharField(
                choices=[("counter", "Счетчик"), ("tarif", "Тариф")],
                default="tarif",
                max_length=50,
                verbose_name="Расчет по",
            ),
        ),
        migrations.AddField(
            model_name="counter",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
        migrations.AddField(
            model_name="tarif",
            name="from_value",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="От"
            ),
        ),
        migrations.AddField(
            model_name="tarif",
            name="to_value",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1000000, verbose_name="До"
            ),
        ),
        migrations.AlterField(
            model_name="counter",
            name="value",
            field=models.PositiveIntegerField(verbose_name="Показания"),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_counter",
            field=models.CharField(
                choices=[
                    ("counter", "Счетчик"),
                    ("tarif", "Тариф"),
                    ("day", "Счетчик День"),
                    ("night", "Счетчик Ночь"),
                    ("total", "Итого"),
                ],
                default="tarif",
                max_length=50,
                verbose_name="Расчет",
            ),
        ),
        migrations.DeleteModel(name="DiscreteConfiguration",),
    ]
