# Generated by Django 4.1.5 on 2023-02-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0008_alter_tarif_options_remove_item_day_night_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counter",
            options={
                "ordering": ["-created"],
                "verbose_name": "Показания счетчика",
                "verbose_name_plural": "Показания счетчиков",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["id"],
                "verbose_name": "Конфигурация для расчета",
                "verbose_name_plural": "Конфигурации для расчета",
            },
        ),
        migrations.AddField(
            model_name="tarif",
            name="el_counter_discrete",
            field=models.BooleanField(
                default=False, verbose_name="Тариф зависит от потребления"
            ),
        ),
        migrations.AlterField(
            model_name="counter",
            name="type",
            field=models.CharField(
                choices=[
                    ("counter", "Однотарифный"),
                    ("day", "День"),
                    ("night", "Ночь"),
                ],
                default="flat",
                max_length=15,
                verbose_name="Тип счетчика",
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="value",
            field=models.FloatField(verbose_name="Тариф"),
        ),
    ]
