# Generated by Django 4.1.5 on 2023-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0010_alter_tarif_el_counter_discrete_alter_tarif_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="item",
            field=models.CharField(
                choices=[
                    ("electricity", "Электричество"),
                    ("water", "Вода"),
                    ("gas", "Газ"),
                    ("kv", "Квартплата"),
                    ("tbo", "ТБО"),
                    ("domofon", "Домофон"),
                    ("inet", "Интернет"),
                    ("other", "Другой вид оплаты"),
                ],
                max_length=20,
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="value",
            field=models.FloatField(verbose_name="Тариф "),
        ),
    ]
