# Generated by Django 4.1.5 on 2023-02-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compay", "0011_alter_info_item_alter_tarif_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debts",
            options={
                "ordering": ["created"],
                "verbose_name": "Долг",
                "verbose_name_plural": "Долг",
            },
        ),
        migrations.AddField(
            model_name="topay",
            name="calculation",
            field=models.CharField(blank=True, max_length=250, verbose_name="Расчёт"),
        ),
        migrations.AlterField(
            model_name="debts",
            name="value",
            field=models.FloatField(default=0, verbose_name="Долг"),
        ),
        migrations.AlterField(
            model_name="info",
            name="item_provider",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Название организации"
            ),
        ),
        migrations.AlterField(
            model_name="payed",
            name="value",
            field=models.FloatField(default=0, verbose_name="Оплачено"),
        ),
        migrations.AlterField(
            model_name="topay",
            name="value",
            field=models.FloatField(default=0, verbose_name="Расчет для оплаты"),
        ),
    ]
